import { Payout, PeerConfirmation, SmsLog } from '../types';

const now = Date.now();

export const DEMO_PAYOUTS: Payout[] = [
  {
    id: 'claim-demo-101',
    workerId: 'demo-worker-ramesh-101',
    workerName: 'Ramesh Kumar',
    zoneId: 'hyd-charminar',
    zoneName: 'Charminar Heritage Bazaar',
    riskScore: 76,
    weatherSnapshot: { temp: 41, rain: 28, condition: 'Severe Monsoon Inundation' },
    tier: 'Tier 2 (60%)',
    percentage: 60,
    dailyWage: 750,
    amount: 450,
    status: 'pending_confirmation',
    confirmationsCount: 0,
    requiredConfirmations: 2,
    confirmedBy: [],
    timestamp: 'Today, 11:20 IST',
    createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
    smsDispatched: true,
    smsText: 'RainGuard: Weather distress detected in Charminar. Awaiting peer confirmations to disburse ₹450.',
  },
  {
    id: 'claim-demo-102',
    workerId: 'demo-worker-lakshmi-102',
    workerName: 'Lakshmi Devi',
    zoneId: 'hyd-koti',
    zoneName: 'Koti Sultan Bazaar',
    riskScore: 68,
    weatherSnapshot: { temp: 39.5, rain: 22, condition: 'Extreme Heat & Waterlogging' },
    tier: 'Tier 1 (30%)',
    percentage: 30,
    dailyWage: 600,
    amount: 180,
    status: 'pending_confirmation',
    confirmationsCount: 0,
    requiredConfirmations: 2,
    confirmedBy: [],
    timestamp: 'Today, 10:45 IST',
    createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
    smsDispatched: true,
    smsText: 'RainGuard: Weather distress detected in Koti. Awaiting peer confirmations to disburse ₹180.',
  },
  {
    id: 'payout-demo-103',
    workerId: 'demo-worker-ramesh-101',
    workerName: 'Ramesh Kumar',
    zoneId: 'hyd-charminar',
    zoneName: 'Charminar Heritage Bazaar',
    riskScore: 78,
    weatherSnapshot: { temp: 42.5, rain: 26, condition: 'High Heat Stress & Sudden Rain' },
    tier: 'Tier 2 (60%)',
    percentage: 60,
    dailyWage: 750,
    amount: 450,
    status: 'disbursed',
    confirmationsCount: 2,
    requiredConfirmations: 2,
    confirmedBy: ['demo-worker-lakshmi-102', 'demo-worker-suresh-103'],
    timestamp: 'Yesterday, 14:30 IST',
    createdAt: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
    smsDispatched: true,
    smsText: 'RainGuard: ₹450 credited to your wallet after peer verification.',
  },
];

export const DEMO_CONFIRMATIONS: PeerConfirmation[] = [
  {
    id: 'conf-demo-1',
    payoutId: 'payout-demo-103',
    zoneId: 'hyd-charminar',
    verifierId: 'demo-worker-lakshmi-102',
    verifierName: 'Lakshmi Devi',
    verifierTrade: 'Flower Garland Stall',
    verifierLat: 17.3615,
    verifierLng: 78.4746,
    conditionReported: 'heavy_rain',
    confirmed: true,
    fraudCheckPassed: true,
    timestamp: 'Yesterday, 14:15 IST',
  },
];

export const DEMO_SMS_LOGS: SmsLog[] = [
  {
    id: 'sms-demo-1',
    workerId: 'demo-worker-ramesh-101',
    workerName: 'Ramesh Kumar',
    phone: '+91 98480 23145',
    language: 'en',
    message: 'RainGuard: ₹450 credited after peer verification in Charminar.',
    type: 'PAYOUT_CREDITED',
    timestamp: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
    delivered: true,
  },
];
